
services:
  # Base de datos PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: capygaming-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    #ports:
      #- "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/bd/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - capygaming-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend Node.js
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: capygaming-backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
      BACKEND_URL: ${BACKEND_URL}
      MERCADOPAGO_ACCESS_TOKEN: ${MERCADOPAGO_ACCESS_TOKEN}
      MERCADOPAGO_PUBLIC_KEY: ${MERCADOPAGO_PUBLIC_KEY}
      MERCADOPAGO_WEBHOOK_SECRET: ${MERCADOPAGO_WEBHOOK_SECRET}
      ALLOW_UNSIGNED_WEBHOOKS: ${ALLOW_UNSIGNED_WEBHOOKS}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
    ports:
      - "3001:3001"
    networks:
      - capygaming-network
    volumes:
      - ./backend:/app
      - /app/node_modules


  # Frontend Vue.js con Nginx
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # Usa nginx.conf (con proxy) para Docker local
        - NGINX_CONF=nginx.conf
    container_name: capygaming-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - capygaming-network

# Volúmenes persistentes
volumes:
  postgres_data:
    driver: local

# Red personalizada
networks:
  capygaming-network:
    driver: bridge