# Render Blueprint para CapyGaming
# Este archivo permite desplegar toda la aplicación con un solo click

services:
  # 1. Backend API (Node.js + Express)
  - type: web
    name: capygaming-backend
    runtime: node
    plan: free
    region: oregon
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    healthCheckPath: /api/health
    envVars:
      # Estas variables se configuran automáticamente
      - key: NODE_ENV
        value: production

      - key: PORT
        value: 3001

      # Base de datos (se vincula con el servicio PostgreSQL de abajo)
      - key: DATABASE_URL
        fromDatabase:
          name: capygaming-db
          property: connectionString

      # Extraer partes individuales de DATABASE_URL para pool.js
      - key: DB_USER
        fromDatabase:
          name: capygaming-db
          property: user

      - key: DB_HOST
        fromDatabase:
          name: capygaming-db
          property: host

      - key: DB_NAME
        fromDatabase:
          name: capygaming-db
          property: database

      - key: DB_PASSWORD
        fromDatabase:
          name: capygaming-db
          property: password

      - key: DB_PORT
        value: 5432

      # JWT Secret (se genera automáticamente)
      - key: JWT_SECRET
        generateValue: true

      # URLs de la aplicación (actualizar después del deploy)
      - key: FRONTEND_URL
        value: https://capygaming-frontend.onrender.com

      - key: BACKEND_URL
        sync: false

      # MercadoPago (configurar manualmente después)
      - key: MERCADOPAGO_ACCESS_TOKEN
        sync: false

      - key: MERCADOPAGO_PUBLIC_KEY
        sync: false

      - key: MERCADOPAGO_WEBHOOK_SECRET
        sync: false

      - key: ALLOW_UNSIGNED_WEBHOOKS
        value: false

      # Email (configurar manualmente después)
      - key: EMAIL_USER
        sync: false

      - key: EMAIL_PASS
        sync: false

  # 2. Frontend (Vue.js + Vite - Static Site)
  - type: web
    name: capygaming-frontend
    runtime: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      # URL del backend (actualizar después del deploy)
      - key: VITE_API_URL
        value: https://capygaming-backend.onrender.com
    routes:
      # Vue Router: redirigir todas las rutas a index.html
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: capygaming-db
    databaseName: capygaming
    user: capygaming_user
    plan: free
    region: oregon
