export const productos = [
    {
    id: 1,
    nombre: "Notebook Acer Aspire 3 15.6 AMD Ryzen 5 7520U 8GB DDR5 SSD 512GB",
    precio: 850000,
    imagenes: [
    "https://imgur.com/Eyh2lUh.jpg",
    "https://imgur.com/S7HTO9I.jpg"
    ],
    categoria: "Notebooks",
    subcategoria: "ACER",
    marca: "ACER",
    stock: 30,
    },
    {
    id: 2,
    nombre:
    "Notebook Asus Rog Strix G16 16 32GB 275HX Intel Core ULTRA 9 DDR5 1TB",
    precio: 5700650,
    imagenes: [
    "https://imgur.com/UAnNw2n.jpg",
    "https://imgur.com/uKYkZ0I.jpg",
    ],
    categoria: "Notebooks",
    subcategoria: "ASUS",
    marca: "ASUS",
    stock: 25,
    },
    {
    id: 3,
    nombre:
    "Notebook Lenovo IdeaPad Slim 3 15.6 Intel Core i3 N305 8GB SSD 256GB Win11 Arctic Grey 15IAN8 82XB008LUS",
    precio: 620900,
    imagenes: [
    "https://imgur.com/2sqMV0M.jpg",
    "https://imgur.com/0anu0bk.jpg",
    ],
    categoria: "Notebooks",
    subcategoria: "Lenovo",
    marca: "Lenovo",
    stock: 35,
    },
    {
    id: 4,
    nombre:
    "Notebook Asus Vivobook Go 15 15.6 AMD Ryzen 5 7520U 8GB DDR5 SSD 1TB Win11 Teclado Español E1504FA-NJ179W-F",
    precio: 870900,
    imagenes: [
    "https://imgur.com/g1GTbOs.jpg",
    "https://imgur.com/ETiqu7r.jpg",
    ],
    categoria: "Notebooks",
    subcategoria: "ASUS",
    marca: "ASUS",
    stock: 15,
    },
    {
    id: 5,
    nombre:
    "Kit Mother ASUS H610M-K + Procesador Intel Core I5 12400F 4.4GHz Turbo (Sin Video Integrado)",
    precio: 280960,
    imagenes: ["https://imgur.com/myKUDBn.jpg"],
    categoria: "Hardware",
    subcategoria: "Kit Actualizacion",
    marca: "ASUS",
    stock: 125,
    },
    {
    id: 6,
    nombre:
    "Kit Procesador Intel Core I7 12700 4.9GHz Turbo (Con Video Integrado) + Mother ASUS PRIME H610M-K CSM DDR4 S1700 + 2x Memoria Team DDR4 8GB 3200Mhz Vulcan ASUS TUF Alliance CL16",
    precio: 595800,
    imagenes: ["https://imgur.com/V27Oray.jpg"],
    categoria: "Hardware",
    subcategoria: "Kit Actualizacion",
    marca: "ASUS",
    stock: 25,
    },
    {
    id: 7,
    nombre:
    "Kit Mother ASUS H610M-K + Procesador Intel Core I7 12700F 4.9GHz Turbo (Sin Video Integrado) + Memoria Team DDR4 8GB 3200Mhz Vulcan ASUS TUF Certificate",
    precio: 530700,
    imagenes: ["https://imgur.com/jJvTs7y.jpg"],
    categoria: "Hardware",
    subcategoria: "Kit Actualizacion",
    marca: "ASUS",
    stock: 105,
    },
    {
    id: 8,
    nombre: "Volante Logitech G923 Trueforce Racing PC/PS4/PS5 + Palanca",
    precio: 650700,
    imagenes: ["https://imgur.com/ISLYIjp.jpg"],
    categoria: "Perifericos",
    subcategoria: "Volante",
    marca: "Logitech",
    stock: 45,
    },
    {
    id: 9,
    nombre: "Volante Logitech G923 Trueforce Racing PC/PS4/PS5",
    precio: 570700,
    imagenes: ["https://imgur.com/GeP74IQ.jpg"],
    categoria: "Perifericos",
    subcategoria: "Volante",
    marca: "Logitech",
    stock: 40,
    },
    {
    id: 10,
    nombre: "Palanca de Cambios Secuencial y Freno de Mano Logitech RS",
    precio: 298900,
    imagenes: ["https://imgur.com/FC9ANiL.jpg"],
    categoria: "Perifericos",
    subcategoria: "Volante",
    marca: "Logitech",
    stock: 25,
    },
    {
    id: 11,
    nombre: "Disco Sólido SSD Kingston 480GB A400 500MB/s",
    precio: 58000,
    imagenes: ["https://imgur.com/98aoYBH.jpg"],
    categoria: "Hardware",
    subcategoria: "Almacenamiento",
    marca: "Kingston",
    stock: 150,
    },
    {
    id: 12,
    nombre: "Disco Solido SSD M.2 Team 256GB MP33 1600MB/s NVMe PCI-E Gen3 x4",
    precio: 35000,
    imagenes: [
    "https://imgur.com/WA6ZO7n.jpg",
    "https://imgur.com/kDhiBvc.jpg",
    ],
    categoria: "Hardware",
    subcategoria: "Almacenamiento",
    marca: "Team",
    stock: 90,
    },
    {
    id: 13,
    nombre: "Disco Rígido WD 8TB PURPLE 256MB SATA 6.0GB/s",
    precio: 315000,
    imagenes: ["https://imgur.com/9rufi4A.jpg"],
    categoria: "Hardware",
    subcategoria: "Almacenamiento",
    marca: "WD",
    stock: 20,
    },
    {
    id: 14,
    nombre: "Disco Rígido Seagate 4TB Barracuda 256MB SATA 6GB/s",
    precio: 132000,
    imagenes: ["https://imgur.com/nqqMSwj.jpg"],
    categoria: "Hardware",
    subcategoria: "Almacenamiento",
    marca: "Seagate",
    stock: 10,
    },
    {
    id: 15,
    nombre: "Disco Solido SSD Team 256GB GX2 530MB/s",
    precio: 27500,
    imagenes: ["https://imgur.com/Z2Bn9zi.jpg"],
    categoria: "Hardware",
    subcategoria: "Almacenamiento",
    marca: "Team",
    stock: 50,
    },
    {
    id: 16,
    nombre: "Disco Rigido WD 8TB Purple Pro 7.2K RPM 256MB WD8002PURP",
    precio: 352000,
    imagenes: ["https://imgur.com/xbyCVMN.jpg"],
    categoria: "Hardware",
    subcategoria: "Almacenamiento",
    marca: "WD",
    stock: 60,
    },
    {
    id: 17,
    nombre: "Auriculares Logitech H390 Black USB",
    precio: 46000,
    imagenes: ["https://imgur.com/RTefcb0.jpg"],
    categoria: "Perifericos",
    subcategoria: "Auriculares",
    marca: "Logitech",
    stock: 20,
    },
    {
    id: 18,
    nombre:
    "Mouse Logitech G903 Wireless 2.4Ghz Lightspeed 1ms HERO 25K 110g 24Hs",
    precio: 15000,
    imagenes: ["https://imgur.com/0LOdaL4.jpg"],
    categoria: "Perifericos",
    subcategoria: "Mouse",
    marca: "Logitech",
    stock: 250,
    },
    {
    id: 19,
    nombre: "Mouse Redragon Griffin M607 RGB Black",
    precio: 25000,
    imagenes: ["https://imgur.com/OO24ubn.jpg"],
    categoria: "Perifericos",
    subcategoria: "Mouse",
    marca: "Redragon",
    stock: 200,
    },
    {
    id: 20,
    nombre: "Microfono Redragon Blazar GM300 Condensador USB",
    precio: 110500,
    imagenes: ["https://imgur.com/oxVZrPB.jpg"],
    categoria: "Perifericos",
    subcategoria: "Microfono",
    marca: "Redragon",
    stock: 30,
    },
    {
    id: 21,
    nombre:
    "Auriculares Logitech G733 Wireless Lightspeed LightSync RGB Blue 29Hs",
    precio: 300300,
    imagenes: ["https://imgur.com/JmtIh5i.jpg"],
    categoria: "Perifericos",
    subcategoria: "Auriculares",
    marca: "Logitech",
    stock: 10,
    },
    {
    id: 22,
    nombre:
    "Microfono Logitech Yeti GX Premium Supercardioide Black RGB LightSync USB-C",
    precio: 169000,
    imagenes: ["https://imgur.com/6wiDazR.jpg"],
    categoria: "Perifericos",
    subcategoria: "Microfono",
    marca: "Logitech",
    stock: 100,
    },
    {
    id: 23,
    nombre:
    "Micrófono SteelSeries Alias PRO Condensador Studio Quality XLR Stream Mixer RGB Niveles de Led ANC USB-C",
    precio: 500900,
    imagenes: ["https://imgur.com/LynMhXR.jpg"],
    categoria: "Perifericos",
    subcategoria: "Microfono",
    marca: "SteelSeries",
    stock: 250,
    },
    {
    id: 24,
    nombre:
    "Mouse SteelSeries Aerox 9 MOBA/MMO Wireless 2.4Ghz Bluetooth Ultra LightWeight AquaBarrier IP54 Sensor TrueMove Air RGB 89g 180Hs",
    precio: 200300,
    imagenes: ["https://imgur.com/NWZDaEm.jpg"],
    categoria: "Perifericos",
    subcategoria: "Mouse",
    marca: "SteelSeries",
    stock: 250,
    },
    {
    id: 25,
    nombre: "Mouse Pad Logitech G Powerplay Carga Inalambrica 321x344mm",
    precio: 200000,
    imagenes: ["https://imgur.com/EpMZglD.jpg"],
    categoria: "Perifericos",
    subcategoria: "Mouse Pad",
    marca: "Logitech",
    stock: 350,
    },
    {
    id: 26,
    nombre: "Mouse Pad Logitech XL Lavanda 700x300mm",
    precio: 30000,
    imagenes: ["https://imgur.com/UvwL1bG.jpg"],
    categoria: "Perifericos",
    subcategoria: "Mouse Pad",
    marca: "Logitech",
    stock: 1250,
    },
    {
    id: 27,
    nombre: "Teclado Redragon K509 Dyaus Español Retroiluminado 7 Colores",
    precio: 30000,
    imagenes: ["https://imgur.com/nVc4nPP.jpg"],
    categoria: "Perifericos",
    subcategoria: "Teclado",
    marca: "Redragon",
    stock: 500,
    },
    {
    id: 28,
    nombre:
    "Combo Redragon S129 3 en 1 Teclado K630 + Mouse M607 White + Auriculares H350 RGB White",
    precio: 110000,
    imagenes: ["https://imgur.com/Cy7ga09.jpg"],
    categoria: "Perifericos",
    subcategoria: "Combo",
    marca: "Redragon",
    stock: 150,
    },
    {
    id: 29,
    nombre: "Webcam Logitech Brio 300 Rose 1080p/30 fps 720p/60fps USB-C",
    precio: 80000,
    imagenes: ["https://imgur.com/MiDhsHl.jpg"],
    categoria: "Perifericos",
    subcategoria: "Webcam",
    marca: "Logitech",
    stock: 50,
    },
    {
    id: 30,
    nombre: "Webcam Logitech MX Brio UHD RightLight 5 4K HDR 1080p/60FPS USB-C",
    precio: 260000,
    imagenes: ["https://imgur.com/42m8cBh.jpg"],
    categoria: "Perifericos",
    subcategoria: "Webcam",
    marca: "Logitech",
    stock: 150,
    },
    {
    id: 31,
    nombre: "Webcam Elgato MK.2 1080p 60fps HDR DSLR USB",
    precio: 215000,
    imagenes: ["https://imgur.com/z9szBaK.jpg"],
    categoria: "Perifericos",
    subcategoria: "Webcam",
    marca: "Elgato",
    stock: 280,
    },
    {
    id: 32,
    nombre:
    "Parlante JBL Charge 5 Black Bluetooth 5.2 Resistente Polvo/Agua IP67 40W 20Hs",
    precio: 280000,
    imagenes: ["https://imgur.com/K3s4EJ5.jpg"],
    categoria: "Perifericos",
    subcategoria: "Parlante",
    marca: "JBL",
    stock: 750,
    },
    {
    id: 33,
    nombre: "Parlante Logitech Ultimate Ears Megaboom 4 Black",
    precio: 330000,
    imagenes: ["https://imgur.com/g3rsDvg.jpg"],
    categoria: "Perifericos",
    subcategoria: "Parlante",
    marca: "Logitech",
    stock: 10,
    },
    {
    id: 34,
    nombre:
    "Parlante JBL CLIP 5 Bluetooth 5.3 Resistente Polvo/Agua IP67 Black 15Hs",
    precio: 81000,
    imagenes: ["https://imgur.com/5cF7Jf7.jpg"],
    categoria: "Perifericos",
    subcategoria: "Parlante",
    marca: "JBL",
    stock: 20,
    },
    {
    id: 35,
    nombre:
    "Auriculares SteelSeries Arctis Nova PRO Dualconnect Wireless 2.4Ghz Bluetooth White Infinity Power System 44Hs Hot-swap PC/PS/XBOX/MAC/Switch",
    precio: 640000,
    imagenes: ["https://imgur.com/mPcvW5f.jpg"],
    categoria: "Perifericos",
    subcategoria: "Auriculares",
    marca: "SteelSeries",
    stock: 50,
    },
    {
    id: 36,
    nombre:
    "Teclado Hipermagnético SteelSeries Apex PRO TKL 3 Wireless 2.4Ghz Bluetooth Black RGB Omnipoint 3.0 Hall Effect",
    precio: 360000,
    imagenes: ["https://imgur.com/tgr6iTs.jpg"],
    categoria: "Perifericos",
    subcategoria: "Teclado",
    marca: "SteelSeries",
    stock: 1250,
    },
    {
    id: 37,
    nombre: "Combo Logitech teclado y mouse POP Icon Wireless Graphite",
    precio: 82000,
    imagenes: ["https://imgur.com/bCvPsNg.jpg"],
    categoria: "Perifericos",
    subcategoria: "Combo",
    marca: "Logitech",
    stock: 200,
    },
    {
    id: 38,
    nombre: "Combo Logitech teclado y mouse POP Icon Wireless White",
    precio: 82000,
    imagenes: ["https://imgur.com/bpkY1rF.jpg"],
    categoria: "Perifericos",
    subcategoria: "Combo",
    marca: "Logitech",
    stock: 150,
    },
    {
    id: 39,
    nombre: "Gabinete Cougar MX410 Mesh-G RGB 4x120mm ARGB Fans",
    precio: 90000,
    imagenes: ["https://imgur.com/myhGaR8.jpg"],
    categoria: "Hardware",
    subcategoria: "Gabinetes",
    marca: "Cougar",
    stock: 120,
    },
    {
    id: 40,
    nombre: "Gabinete Corsair 6500D Airflow TG Super Mid-Tower White",
    precio: 290000,
    imagenes: ["https://imgur.com/QkmxA0G.jpg"],
    categoria: "Hardware",
    subcategoria: "Gabinetes",
    marca: "Corsair",
    stock: 320,
    },
    {
    id: 41,
    nombre:
    "Gabinete HYTE Y70 TOUCH INFINITE Snow White Vidrio Templado Pantalla Tactil 2.5K LCD IPS 60Hz Inc. Cable Riser PCIe 4x16 USB-C 3.2",
    precio: 620000,
    imagenes: ["https://imgur.com/KmdypvX.jpg"],
    categoria: "Hardware",
    subcategoria: "Gabinetes",
    marca: "HYTE",
    stock: 920,
    },
    {
    id: 42,
    nombre:
    "Gabinete HYTE Y70 TOUCH INFINITE Black Vidrio Templado Pantalla Tactil 2.5K LCD IPS 60Hz Inc. Cable Riser PCIe 4x16 USB-C 3.2",
    precio: 620000,
    imagenes: ["https://imgur.com/tNc2Dfb.jpg"],
    categoria: "Hardware",
    subcategoria: "Gabinetes",
    marca: "HYTE",
    stock: 250,
    },
    {
    id: 43,
    nombre: "Mouse Pad Glorious 2 3XL Stitched Black 1220x610mm",
    precio: 90000,
    imagenes: ["https://imgur.com/81r6sVC.jpg"],
    categoria: "Perifericos",
    subcategoria: "Mouse Pad",
    marca: "Glorious",
    stock: 750,
    },
    {
    id: 44,
    nombre:
    "Joystick XBOX Wireless Bluetooth DOOM The Dark Ages PC/XBOX Serie S/X/One",
    precio: 203000,
    imagenes: ["https://imgur.com/DnEXdTJ.jpg"],
    categoria: "Perifericos",
    subcategoria: "Joystick",
    marca: "XBOX",
    stock: 590,
    },
    {
    id: 45,
    nombre:
    "Teclado Mecanico Glorious GMMK3 HE 75% RGB Hall Efect 8K Hz White US",
    precio: 240000,
    imagenes: ["https://imgur.com/gbOLIqO.jpg"],
    categoria: "Perifericos",
    subcategoria: "Teclado",
    marca: "Glorious",
    stock: 290,
    },
    {
    id: 46,
    nombre: "Silla Gamer Cooler Master Caliber X1C Grey 4D (Peso MAX 150Kg)",
    precio: 500000,
    imagenes: [
    "https://imgur.com/3aOAG3d.jpg",
    "https://imgur.com/HuJpgbW.jpg",
    ],
    categoria: "Gaming",
    subcategoria: "Silla",
    marca: "Cooler Master",
    stock: 150,
    },
    {
    id: 47,
    nombre:
    "Silla Gamer Noblechairs EPIC Fallout Nuka Cola Edition (sin almohadones) (Peso MAX. 120kg)",
    precio: 680000,
    imagenes: [
    "https://imgur.com/weix9W3.jpg",
    "https://imgur.com/QGFnzgV.jpg",
    ],
    categoria: "Gaming",
    subcategoria: "Silla",
    marca: "Noblechairs",
    stock: 80,
    },
    {
    id: 48,
    nombre:
    "Silla Gamer Vertagear SL3800 HygennX Negro Carbon Ergonomic (Peso MAX. 100kg)",
    precio: 380000,
    imagenes: [
    "https://imgur.com/tou9RYL.jpg",
    "https://imgur.com/G3dHlOZ.jpg",
    ],
    categoria: "Gaming",
    subcategoria: "Silla",
    marca: "Vertagear",
    stock: 70,
    },
    {
    id: 49,
    nombre:
    "Silla Gamer Razer Iskur V2 X Tela 2D Gris y Negro Ergonomic (Peso MAX. 136Kg)",
    precio: 520000,
    imagenes: ["https://imgur.com/3XryTWJ.jpg"],
    categoria: "Gaming",
    subcategoria: "Silla",
    marca: "Razer",
    stock: 50,
    },
    {
    id: 50,
    nombre: "Procesador AMD Ryzen 5 4500 + Wraith Stealth Cooler AM4",
    precio: 100000,
    imagenes: ["https://imgur.com/tN6QbsA.jpg"],
    categoria: "Hardware",
    subcategoria: "Procesadores",
    marca: "AMD",
    stock: 350,
    },
    {
    id: 51,
    nombre:
    "Procesador AMD Ryzen 9 7950X 5.7GHz AM5 - No incluye Cooler - C/Video",
    precio: 840000,
    imagenes: [
    "https://imgur.com/L5azYa2.jpg",
    "https://imgur.com/Ot0nNni.jpg",
    ],
    categoria: "Hardware",
    subcategoria: "Procesadores",
    marca: "AMD",
    stock: 250,
    },
    {
    id: 52,
    nombre:
    "Procesador AMD Ryzen 7 9800X3D 5.2GHz Turbo AM5 - No Incluye Cooler",
    precio: 720000,
    imagenes: ["https://imgur.com/BTIfrS6.jpg"],
    categoria: "Hardware",
    subcategoria: "Procesadores",
    marca: "AMD",
    stock: 450,
    },
    {
    id: 53,
    nombre: "UPS con Estabilizador Lyonn Ctb 800ap 800v LED",
    precio: 80000,
    imagenes: ["https://imgur.com/6vMADnh.jpg"],
    categoria: "Hardware",
    subcategoria: "Energia",
    marca: "Lyonn",
    stock: 750,
    },
    {
    id: 54,
    nombre: "UPS con Estabilizador Lyonn Ctb 2000ap 2000v Display Lcd",
    precio: 322000,
    imagenes: ["https://imgur.com/oLgbs79.jpg"],
    categoria: "Hardware",
    subcategoria: "Energia",
    marca: "Lyonn",
    stock: 650,
    },
    {
    id: 55,
    nombre: "Monitor LG 28'' Dual Ergo 28MQ780-B SDQHD Nano IPS",
    precio: 1109000,
    imagenes: [
    "https://imgur.com/tbNX7Z9.jpg",
    "https://imgur.com/ASw8gCn.jpg",
    ],
    categoria: "Monitores",
    subcategoria: "LG",
    marca: "LG",
    stock: 30,
    },
    {
    id: 56,
    nombre:
    "Monitor Gamer AsRock Phantom PG27QFT2A 27 pulgadas QHD IPS 1440p 180Hz FreeSync Antena WiFi Integrada Base Regulable",
    precio: 410000,
    imagenes: ["https://imgur.com/ogJU422.jpg"],
    categoria: "Monitores",
    subcategoria: "AsRock",
    marca: "AsRock",
    stock: 50,
    },
    {
    id: 57,
    nombre:
    "Monitor Gamer Samsung Odyssey G8 34 pulgadas OLED UWQHD Curvo 1800R 175Hz AMD Freesync Premium",
    precio: 3287000,
    imagenes: ["https://imgur.com/9wiCBO5.jpg"],
    categoria: "Monitores",
    subcategoria: "Samsung",
    marca: "Samsung",
    stock: 20,
    },
    {
    id: 58,
    nombre:
    "Monitor LG 49WQ95C-W 49 pulgadas 5120x1440 IPS Curvo 3800R Freesync Premium Pro",
    precio: 3167000,
    imagenes: ["https://imgur.com/BzP78TQ.jpg"],
    categoria: "Monitores",
    subcategoria: "LG",
    marca: "LG",
    stock: 250,
    },
    {
    id: 59,
    nombre: "Mother ASUS ROG CROSSHAIR X670E HERO AM5",
    precio: 884000,
    imagenes: ["https://imgur.com/8GyWuKI.jpg"],
    categoria: "Hardware",
    subcategoria: "Motherboard",
    marca: "ASUS",
    stock: 6500,
    },
    {
    id: 60,
    nombre: "Mother ASUS ROG STRIX X670E-E GAMING WIFI AM5 DDR5",
    precio: 708000,
    imagenes: ["https://imgur.com/A1BnLAE.jpg"],
    categoria: "Hardware",
    subcategoria: "Motherboard",
    marca: "ASUS",
    stock: 1250,
    },
    {
    id: 61,
    nombre: "Mother ASUS TUF GAMING A620M-PLUS WIFI AM5 DDR5",
    precio: 182000,
    imagenes: ["https://imgur.com/POMSQV9.jpg"],
    categoria: "Hardware",
    subcategoria: "Motherboard",
    marca: "ASUS",
    stock: 2500,
    },
    {
    id: 62,
    nombre: "Impresora Multifuncion Laser Brother DCP-1617NW Mono B&N WiFi",
    precio: 468900,
    imagenes: ["https://imgur.com/DT8C2tr.jpg"],
    categoria: "Impresoras",
    subcategoria: "Laser",
    marca: "Brother",
    stock: 19,
    },
    {
    id: 63,
    nombre: "Impresora Multifuncion HP Smart Tank 580 Sistema Continuo",
    precio: 339000,
    imagenes: ["https://imgur.com/ufSFB1p.jpg"],
    categoria: "Impresoras",
    subcategoria: "Tinta",
    marca: "HP",
    stock: 10,
    },
    {
    id: 64,
    nombre: "Stream Deck XL 32 Botones Customizables LCD Elgato",
    precio: 440000,
    imagenes: ["https://imgur.com/2UpYSns.jpg"],
    categoria: "Perifericos",
    subcategoria: "StreamDeck",
    marca: "Elgato",
    stock: 2500,
    },
    {
    id: 65,
    nombre: "Stream Deck PLUS 8 Botones Customizables LCD Elgato",
    precio: 350000,
    imagenes: ["https://imgur.com/RkaCLf9.jpg"],
    categoria: "Perifericos",
    subcategoria: "StreamDeck",
    marca: "Elgato",
    stock: 290,
    },
    {
    id: 66,
    nombre: "Stream Deck PLUS 8 Botones Customizables White LCD Elgato",
    precio: 365000,
    imagenes: ["https://imgur.com/MgO0oPQ.jpg"],
    categoria: "Perifericos",
    subcategoria: "StreamDeck",
    marca: "Elgato",
    stock: 980,
    },
    {
    id: 67,
    nombre:
    "Fuente ADATA XPG 1200W 80 Plus Gold Full Modular ATX 3.0 PCIe 5.0 CORE REACTOR II",
    precio: 270000,
    imagenes: ["https://imgur.com/0Kw1lAq.jpg"],
    categoria: "Hardware",
    subcategoria: "Fuentes",
    marca: "ADATA",
    stock: 820,
    },
    {
    id: 68,
    nombre:
    "Fuente Be Quiet 1000W 80 Plus Platinum STRAIGHT POWER 12 Full Modular ATX 3.1 PCIe 5.1",
    precio: 282000,
    imagenes: ["https://imgur.com/QFOHjip.jpg"],
    categoria: "Hardware",
    subcategoria: "Fuentes",
    marca: "Be Quiet",
    stock: 250,
    },
    {
    id: 69,
    nombre:
    "Fuente Corsair 1000W 80 Plus Gold RM1000X SHIFT Full Modular ATX 3.1 PCIe 5.1",
    precio: 329000,
    imagenes: ["https://imgur.com/UzGvwJH.jpg"],
    categoria: "Hardware",
    subcategoria: "Fuentes",
    marca: "Corsair",
    stock: 260,
    },
    {
    id: 70,
    nombre: "Placa de Video Zotac GeForce RTX 5080 16GB GDDR7 Solid OC",
    precio: 1873200,
    imagenes: [
    "https://imgur.com/EhjFFuV.jpg",
    "https://imgur.com/TfUVpTH.jpg",
    ],
    categoria: "Hardware",
    subcategoria: "Placas de Video",
    marca: "Zotac",
    stock: 20,
    },
    {
    id: 71,
    nombre:
    "Placa de Video Zotac GeForce RTX 5080 16GB GDDR7 AMP EXTREME INFINITY",
    precio: 2021000,
    imagenes: [
    "https://imgur.com/jMqKCmZ.jpg",
    "https://imgur.com/J9IwJhf.jpg",
    ],
    categoria: "Hardware",
    subcategoria: "Placas de Video",
    marca: "Zotac",
    stock: 150,
    },
    {
    id: 72,
    nombre:
    "Joystick PS5 Sony Dualsense Wireless Bluetooth Cobalt Blue Original USB-C",
    precio: 113000,
    imagenes: ["https://imgur.com/yslX8Am.jpg"],
    categoria: "Perifericos",
    subcategoria: "Joystick",
    marca: "Sony",
    stock: 120,
    },
    {
    id: 73,
    nombre:
    "Joystick PS5 Sony Dualsense Wireless Bluetooth Volcanic Red Original USB-C",
    precio: 113000,
    imagenes: ["https://imgur.com/1H4VtSu.jpg"],
    categoria: "Perifericos",
    subcategoria: "Joystick",
    marca: "Sony",
    stock: 50,
    },
    {
    id: 74,
    nombre: "Placa de Red Tp-Link TX401 Pcie Red 10 Gigabit",
    precio: 85000,
    imagenes: ["https://imgur.com/BMs59Ns.jpg"],
    categoria: "Conectividad",
    subcategoria: "Placas de Red",
    marca: "TP-Link",
    stock: 1050,
    },
    {
    id: 75,
    nombre:
    "Placa de Video ASUS ROG GeForce RTX 5090 32GB GDDR7 ASTRAL OC Liquid Cooling",
    precio: 4942000,
    imagenes: [
    "https://imgur.com/Lt12nsv.jpg",
    "https://imgur.com/N93f1hG.jpg",
    ],
    categoria: "Hardware",
    subcategoria: "Placas de Video",
    marca: "ASUS",
    stock: 250,
    },
    {
    id: 76,
    nombre: "Impresora Multifuncion Pantum M6509NW Laser Monocromatica",
    precio: 232000,
    imagenes: ["https://imgur.com/u43k3RK.jpg"],
    categoria: "Impresoras",
    subcategoria: "Laser",
    marca: "Pantum",
    stock: 30,
    },
    {
    id: 77,
    nombre: "Adaptador de Red Archer T4U Tp-Link AC1300 Dual Band USB",
    precio: 31000,
    imagenes: ["https://imgur.com/Po9PRWJ.jpg"],
    categoria: "Conectividad",
    subcategoria: "Adaptador WiFi",
    marca: "Tp-Link",
    stock: 255,
    },
    {
    id: 78,
    nombre: "Adaptador WiFi Tp-Link Archer T2U AC600 Nano USB 2.0",
    precio: 16000,
    imagenes: ["https://imgur.com/Lduf3C0.jpg"],
    categoria: "Conectividad",
    subcategoria: "Adaptador WiFi",
    marca: "Tp-Link",
    stock: 1200,
    },
    {
    id: 79,
    nombre:
    "Cooler FAN XYZ VORTEX PRO 120mm White Reversed Airflow ARGB KIT X3",
    precio: 95000,
    imagenes: ["https://imgur.com/bkAOqeI.jpg"],
    categoria: "Hardware",
    subcategoria: "Refrigeracion",
    marca: "XYZ",
    stock: 50,
    },
    {
    id: 80,
    nombre:
    "Disco Solido SSD M.2 ADATA 2TB XPG MARS 980 STORM 14000MB/s NVMe PCIe Gen5 x4 Water Cooled Heatsink",
    precio: 382000,
    imagenes: ["https://imgur.com/YFATVFT.jpg"],
    categoria: "Hardware",
    subcategoria: "Almacenamiento",
    marca: "ADATA",
    stock: 450,
    },
    {
    id: 81,
    nombre:
    "Memoria ADATA DDR5 48GB (2x24GB) 9200MHz XPG Lancer CUDIMM RGB CL42 Intel XMP 3.0",
    precio: 385000,
    imagenes: ["https://imgur.com/ojiH1VD.jpg"],
    categoria: "Hardware",
    subcategoria: "Memorias RAM",
    marca: "ADATA",
    stock: 20,
    },
    {
    id: 82,
    nombre:
    "Memoria Team DDR5 64GB (2x32GB) 6400MHz T-Force Delta RGB CL34 White Intel XMP 3.0 / AMD EXPO",
    precio: 372000,
    imagenes: ["https://imgur.com/sokFLqq.jpg"],
    categoria: "Hardware",
    subcategoria: "Memorias RAM",
    marca: "Team",
    stock: 2500,
    },
    {
    id: 83,
    nombre:
    "Memoria G.Skill DDR5 64GB (2x32GB) 6000MHz TRIDENT Z5 NEO RGB Black CL36 AMD EXPO/XMP 3.0",
    precio: 302000,
    imagenes: ["https://imgur.com/QGcV8qD.jpg"],
    categoria: "Hardware",
    subcategoria: "Memorias RAM",
    marca: "G.Skill",
    stock: 20,
    },
    {
    id: 84,
    nombre:
    "Memoria G.Skill DDR5 64GB (2x32GB) 6000MHz TRIDENT Z5 NEO RGB White CL36 AMD EXPO/XMP 3.0",
    precio: 370000,
    imagenes: ["https://imgur.com/lj8Oywp.jpg"],
    categoria: "Hardware",
    subcategoria: "Memorias RAM",
    marca: "G.Skill",
    stock: 250,
    },
    {
    id: 85,
    nombre:
    "Cooler FAN Be Quiet! LIGHT WINGS 120mm White ARGB PWM High-speed KIT X3",
    precio: 90000,
    imagenes: ["https://imgur.com/ncOCpGM.jpg"],
    categoria: "Hardware",
    subcategoria: "Refrigeracion",
    marca: "Be Quiet",
    stock: 10,
    },
    {
    id: 86,
    nombre:
    "Cooler FAN Be Quiet! LIGHT WINGS 140mm White ARGB PWM High-speed KIT X3",
    precio: 120000,
    imagenes: ["https://imgur.com/IQK872v.jpg"],
    categoria: "Hardware",
    subcategoria: "Refrigeracion",
    marca: "Be Quiet",
    stock: 1250,
    },
    {
    id: 87,
    nombre:
    "Nintendo Switch 2 Standard 256GB + Cargador",
    precio: 1182000,
    imagenes: ["https://imgur.com/PoOJ3gm.jpg"],
    categoria: "Gaming",
    subcategoria: "Consolas",
    marca: "Nintendo",
    stock: 450,
    },
    {
    id: 88,
    nombre:
    "Nintendo Switch 2 Mario Kart World Bundle 256GB + Cargador ",
    precio: 1258000,
    imagenes: ["https://imgur.com/zlLFmsW.jpg"],
    categoria: "Gaming",
    subcategoria: "Consolas",
    marca: "Nintendo",
    stock: 250,
    },
];